global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'node-exporter' 
    static_configs: 
    - targets: ['nodeexporter:9100']

remote_write:

    - url: 'http://192.168.1.144:8000/v1/write/'
      name: adapter
      queue_config: 
       max_samples_per_send: 1000
       batch_send_deadline: 10s


